---
mappings:
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Data Engineering Tutorials - Code\
    \ Repositories/Datasource Project: Flight Alerts/datasets/preprocessed/flight_alerts_preprocessed"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a510be5d-02fc-45e3-be72-1c48b58a54e8"
- alias: "ri.foundry.main.dataset.9857288a-d355-40cb-ba4b-179d7a1cdeb1"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9857288a-d355-40cb-ba4b-179d7a1cdeb1"
