---
mappings:
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Advanced incremental data processing\
    \ with PySpark in Code Repositories (2024-10-04 16:01:09)/2_multi_inputs_outputs"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a202b4c0-82d4-4619-b481-cf47d282abe3"
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Advanced incremental data processing\
    \ with PySpark in Code Repositories (2024-10-04 16:01:09)/generated_dataset_1"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.dc1eaa1c-bbb8-4630-8a0f-87631a4cb4c6"
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Data Engineering Tutorials - Code\
    \ Repositories/Datasource Project: Flight Alerts/datasets/clean/flight-alerts-clean"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8f02ab63-356f-41ad-bdb4-3e6cb8173390"
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Data Engineering Tutorials - Code\
    \ Repositories/Datasource Project: Flight Alerts/datasets/preprocessed/flight_alerts_preprocessed"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a510be5d-02fc-45e3-be72-1c48b58a54e8"
- alias: "/SOLEX-a8870f/[Notional] RAP Playground/Data Engineering Tutorials - Code\
    \ Repositories/Datasource Project: Flight Alerts/datasets/processed/flight_alerts_processed"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0ea4faca-3c12-4eb3-a46a-eca778cf0536"
- alias: "ri.foundry.main.dataset.9857288a-d355-40cb-ba4b-179d7a1cdeb1"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9857288a-d355-40cb-ba4b-179d7a1cdeb1"
